version: "3"

services:
  permissions:
    image: node:20-alpine
    container_name: permissions
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    # command: sh -c "npm install && npm run start"
    command: sh -c "npm i -g @nestjs/cli && tail -f /dev/null"
    networks:
      - dev

networks:
  dev:
    external: true
